name: Renovate Dependencies

on:
  # schedule:
  #   # Run every day at 2 AM UTC
  #   - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "info"
        type: choice
        options:
          - info
          - debug
          - warn
      dryRun:
        description: "Dry run (no changes made)"
        required: false
        default: false
        type: boolean

jobs:
  renovate:
    name: Renovate Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}

        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Optional: Set log level from workflow input
          LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}
          # Optional: Enable dry run mode
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun || 'false' }}
          # Use GitHub token for API calls
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Enable platform automerge
          # RENOVATE_PLATFORM_AUTOMERGE: true
